

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "docs/.island/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run build"
